spring:
  application:
    name: Vital Magic
  datasource:
    url: jdbc:mysql://localhost:3307/vitalmagic
    username: vitaluser
    password: vitalpass
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
